on: 
  push: 
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: 🛠️ Install dependencies
      run: npm install

    - name: 🚀 Build
      run: npm run build

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.ftp_server}}
        FTP_USERNAME: ${{secrets.ftp_username}}
        FTP_PASSWORD: ${{secrets.ftp_password}}
        LOCAL_DIR: ./dist/spa/
        REMOTE_DIR: ./jinoe.conturetz.com/
        METHOD: sftp
        PORT: 22
